import {
  MessageSquareWarning,
  Link2,
  QrCode,
  Shield,
  Globe,
  Bot,
} from "lucide-react";

import FeatureCard from "./FeatureCard";

function Features() {
  const features = [
    {
      icon: (
        <MessageSquareWarning
          size={36}
          className="text-emerald-400"
        />
      ),
      title: "SMS Scam Detection",
      description:
        "Analyze suspicious SMS messages using Artificial Intelligence and detect phishing attempts before they can harm you.",
    },
    {
      icon: (
        <Link2
          size={36}
          className="text-cyan-400"
        />
      ),
      title: "URL Scanner",
      description:
        "Identify phishing websites instantly using Machine Learning and advanced rule-based analysis.",
    },
    {
      icon: (
        <QrCode
          size={36}
          className="text-orange-400"
        />
      ),
      title: "QR Code Scanner",
      description:
        "Scan QR codes safely and discover hidden malicious links before opening them.",
    },
    {
      icon: (
        <Bot
          size={36}
          className="text-purple-400"
        />
      ),
      title: "AI Risk Analysis",
      description:
        "Receive confidence scores, threat predictions and detailed explanations generated by AI.",
    },
    {
      icon: (
        <Globe
          size={36}
          className="text-green-400"
        />
      ),
      title: "Fake Website Detection",
      description:
        "Detect cloned banking, shopping and login pages designed to steal sensitive information.",
    },
    {
      icon: (
        <Shield
          size={36}
          className="text-red-400"
        />
      ),
      title: "Privacy Protection",
      description:
        "Stay protected with real-time recommendations and risk analysis while browsing online.",
    },
  ];

  return (
    <section className="bg-slate-950 py-24 px-6">

      <div className="max-w-7xl mx-auto">

        <div className="text-center mb-16">

          <h2 className="text-5xl font-bold text-white">
            Core Features
          </h2>

          <p className="text-gray-400 text-lg mt-5 max-w-3xl mx-auto">
            Guardian AI combines Artificial Intelligence,
            Machine Learning and rule-based analysis
            to protect users from modern cyber threats.
          </p>

        </div>

        <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-8">

          {features.map((feature, index) => (
            <FeatureCard
              key={index}
              icon={feature.icon}
              title={feature.title}
              description={feature.description}
            />
          ))}

        </div>

      </div>

    </section>
  );
}

export default Features;