import {
  MessageSquareWarning,
  Link2,
  QrCode,
  Shield,
  Globe,
  Bot,
} from "lucide-react";

import FeatureCard from "./FeatureCard";

function Features() {
  const features = [
    {
      icon: (
        <MessageSquareWarning
          size={32}
          className="text-orange-400"
        />
      ),
      title: "SMS Scam Detection",
      description:
        "Analyze suspicious SMS messages using Artificial Intelligence and detect phishing attempts before they can harm you.",
    },

    {
      icon: (
        <Link2
          size={32}
          className="text-emerald-400"
        />
      ),
      title: "URL Scanner",
      description:
        "Identify phishing websites instantly using Machine Learning and advanced rule-based analysis.",
    },

    {
      icon: (
        <QrCode
          size={32}
          className="text-cyan-400"
        />
      ),
      title: "QR Code Scanner",
      description:
        "Scan QR codes safely and discover hidden malicious links before opening them.",
    },

    {
      icon: (
        <Bot
          size={32}
          className="text-purple-400"
        />
      ),
      title: "AI Risk Analysis",
      description:
        "Receive confidence scores, threat predictions and detailed explanations generated by AI.",
    },

    {
      icon: (
        <Globe
          size={32}
          className="text-red-400"
        />
      ),
      title: "Fake Website Detection",
      description:
        "Detect cloned banking, shopping and login pages designed to steal sensitive information.",
    },

    {
      icon: (
        <Shield
          size={32}
          className="text-green-400"
        />
      ),
      title: "Privacy Protection",
      description:
        "Stay protected with real-time recommendations and risk analysis while browsing online.",
    },
  ];

  return (
    <section className="relative w-full overflow-hidden">

      {/* Background Glow */}

      <div
        className="
          absolute
          top-1/2
          left-[-180px]
          w-[350px]
          h-[350px]
          bg-emerald-500/5
          rounded-full
          blur-3xl
          pointer-events-none
        "
      />

      <div
        className="
          absolute
          bottom-[-100px]
          right-[-100px]
          w-[350px]
          h-[350px]
          bg-purple-500/5
          rounded-full
          blur-3xl
          pointer-events-none
        "
      />

      {/* Main Container */}

      <div className="relative z-10 max-w-6xl mx-auto px-6">

        {/* Header */}

        <div className="text-center mb-10 md:mb-12">

          <div
            className="
              inline-flex
              items-center
              gap-2
              px-4
              py-2
              rounded-full
              bg-emerald-500/10
              border
              border-emerald-500/20
              text-emerald-400
              text-xs
              md:text-sm
              font-semibold
              mb-4
            "
          >
            <Shield size={15} />

            Intelligent Protection
          </div>

          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-white">
            Core Features
          </h2>

          <p
            className="
              text-gray-400
              text-sm
              md:text-base
              mt-4
              max-w-2xl
              mx-auto
              leading-7
            "
          >
            Guardian AI combines Artificial Intelligence,
            Machine Learning and rule-based analysis to
            protect users from modern cyber threats.
          </p>

        </div>

        {/* Feature Cards */}

        <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5 md:gap-6">

          {features.map((feature, index) => (
            <FeatureCard
              key={index}
              icon={feature.icon}
              title={feature.title}
              description={feature.description}
            />
          ))}

        </div>

      </div>

    </section>
  );
}

export default Features;